### ISSUE TITLE
QR Codes erstellen

### ISSUE THREAD

**Issue by Finneah** [Finneah/heppiventcard#1]
## Website
https://www.qrcode-monkey.com/de
## Schema
JSON Format
```
{
   url: "LINK_TO_IMAGE",
   date: "YYYY-MM-DD",
   description: "TEXT",
   name: "EVENTNAME",
}
```

**Comment by Gnatzbert** [comment]
Alles klar mein Schatz das mache ich.

**Comment by Finneah** [comment]
@Gnatzbert ok mein Fehler. Am besten du schreibst in die QRCodes so:
`url=URL&date=YYY-MM-DD&description=DESCRIPTION&name=NAME`
