### ISSUE TITLE
Stempel für volle Stempelkarte bereitstellen

### ISSUE THREAD

**Issue by Finneah** [Finneah/heppiventcard#2]
## Description
Die Stempel sollen als Image / Svg (ist besser) eingebunden werden. 
Die Stempel müssen noch bereit gestellt werden.

**Comment by Gnatzbert** [comment]
![Heppiventcard Platin](https://user-images.githubusercontent.com/55943149/110205311-a3d84600-7e77-11eb-8ef6-013a7429e357.jpg)
![Heppiventcard Gold - Script MT Bold](https://user-images.githubusercontent.com/55943149/110205312-a5097300-7e77-11eb-8a52-b080486e8539.jpg)
![Heppiventcard Mitglied](https://user-images.githubusercontent.com/55943149/110205314-a5a20980-7e77-11eb-9887-0d62dca3d94c.jpg)
Das sind die Icons für volle Stempelkarten
